### ISSUE TITLE
Some issues with > and <

### ISSUE THREAD

**Issue by justbur** [luxbock/evil-cleverparens#21] opened 2015-09-29 12:27 UTC
I've been noticing some odd behavior with > and < in normal state.
1. Can't barf an expression and end up with an empty sexp. This works fine with >
   
   ```
   (func ([)] (a)) => (func ( (a)[)])
   ```
   
   but I can't reverse this operation with <
2. I've had some issues with the point not staying on the point after a barf or a slurp (sorry I can't come up with a working example right now, but I'll post it as soon as I do)

**Comment by luxbock** [comment] 2015-09-29 12:37
The changes I made recently were quite big so there's a good chance I broke
something. I will have to take a look at this later as I won't have access
to a computer for a few days.

**Comment by justbur** [comment] 2015-09-29 12:38
No worries. I'll try to reproduce that other issue in the meantime

**Comment by luxbock** [comment] 2015-10-03 07:25
Looking at this now, I realize that the issue you are referring to is actually behavior that I intentionally introduced. My reasoning was that I could not think of a situation where I would want to perform the operation in your example, i.e. to barf the lone element out of its surrounding form. In deeply nested expressions it is not always obvious when the inner form is the lone element in an outer form, so I thought that I'd rather have the operation be a no-op so that I can then perform the operation that I intended (most likely splicing) instead of having to undo first. This is a rather minor thing of course, so I'd be curious to hear if there are situations where you find this behavior unhelpful.

**Comment by justbur** [comment] 2015-10-03 13:19
It's a little contrived but it's possible you want to do this

``` elisp
(lambda (var)) => (lambda () var)
```

There's certainly nothing incorrect about that. 

The more annoying behavior is that the point doesn't always follows the closing paren after a barf making it hard to repeatedly barf. I had it happen yesterday and should have made note of the situation but I didn't. I'll try to remember to do that next time.

**Comment by justbur** [comment] 2015-10-03 17:10
Here's one that's doing something I don't expect

``` elisp
(let (a)[]
  (b a)
  (c))
```

press `<` and get

``` elisp
(let [(]a)
  (b a))
(c)
```

The resulting parentheses are as I expect but the point moves, so if I hit `<` again quickly I get

``` elisp
([(]let a)
  (b a))
(c)
```

which is not what I wanted. If I undo and start from here

``` elisp
(let[](a)
  (b a))
(c)
```

I now get

``` elisp
([l]et (a))
(b a)
(c)
```

and the point moves backwards again. I expect the point to stay where it is until the moving parenthesis passes it. So starting from the first example hitting `<<` I think should get me here

``` elisp
(let (a)[])
(b a)
(c)
```

which is how `sp-forward-barf-sexp` works. Do you agree or not? 

It seems that the point moves the same distance as the moving parenthesis, so if I try to do that within a large sexp my point can move quite a bit.

**Comment by luxbock** [comment] 2015-10-06 11:27
Hmm I can't reproduce the last issue you mentioned. Are you on the latest version?

**Comment by luxbock** [comment] 2015-10-06 11:32
Also I'd be curious to hear your thoughts on something I'm currently thinking about changing about the behavior of slurping. I think it would make sense if slurping always removed extra spaces (and added one if the item to be slurped was for some reason right next to the closing delimiter, but this is how it works already), so as an example right now calling slurp in:

``` elisp
(foo)         bar
```

results in:

``` elisp
(foo          bar)
```

and with the change it would result in `(foo bar)` instead. This would only affect spaces but not newlines.

**Comment by justbur** [comment] 2015-10-06 12:10
> Hmm I can't reproduce the last issue you mentioned. Are you on the latest version?

Yes, I think it's [this line](https://github.com/luxbock/evil-cleverparens/blob/master/evil-cleverparens.el#L985). Is that necessary?

I'm ok with fixing the spacing after a slurp or a barf, but I think it should be an option that should be disabled. I'm not sure why someone would start in that state with all that spacing.

**Comment by justbur** [comment] 2015-10-06 12:24
I think in the barf operation the point shouldn't move unless you're on the closing paren. That makes it consistent with slurp. If you want to follow then you can use `]` first

**Comment by luxbock** [comment] 2015-10-11 14:35
Ah yeah think I had discovered and fixed this earlier, and forgot I hadn't pushed the fix already. Should work now with the current `master`.

**Comment by justbur** [comment] 2015-10-12 23:07
That's better. thanks

**Closed as completed** 2015-10-21 11:36 UTC
