### ISSUE TITLE
evil-cp-change to end of word with numeral at end of string

### ISSUE THREAD

**Issue by sooheon** [luxbock/evil-cleverparens#27] opened 2015-11-09 14:42 UTC
From

```
"hello|9"
```

with cursor at `|`, pressing `ce` will result in:

```
"hello"|
```

leaving cursor outside the closing quote.

**Comment by luxbock** [comment] 2015-11-17 04:16
I am not able to reproduce this. Perhaps it might be because of some setting in evil like `evil-move-cursor-back` (I tried this one and still was unable to reproduce) that causes it to behave differently for us?

**Comment by sooheon** [comment] 2015-11-17 04:25
Hm, I'm able to reproduce it with `emacs -Q`, `M-x package-initialize` `M-x evil-mode` and `M-x evil-cleverparens-mode` and no other settings. I'm on 25.0.50.1. 

e: to be clear, "cursor at |" means the normal-state cursor is over the numeral ("9").
`cw` works as expected, `co` gives the same wrong result bringing cursor out of closing quotation.

**Comment by luxbock** [comment] 2015-11-17 04:32
Ah you are right! Turns out I was using an outdated version of my own mode. Will investigate.

**Comment by luxbock** [comment] 2015-11-17 04:43
The issue appears to be more general and happens on all delimiters whenever the cursor is on top of the last letter of a word. Note that in regular `evil`, calling `de` on `foo bar` with point on the last `o` of `foo` leaves you with `fo` rather than `fo bar`. I do think that in `evil-cleverparens` what you did should probably behave the way you expected though.

**Comment by luxbock** [comment] 2015-11-17 04:51
Should be fixed now.

**Comment by sooheon** [comment] 2015-11-17 04:59
Wow, good point on that `evil` behavior. That is inexplicably the default in in vim as well... that seems totally inconsistent. Anyways, will test your fix, thanks.

**Comment by sooheon** [comment] 2016-03-07 14:21
Forgot to close :) Works perfectly

**Closed as completed** 2016-03-07 14:21 UTC
